import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
await page.goto('https://www.salesforce.com/in/');
await page.getByLabel('Site tools', { exact: true }).locator('span').filter({ hasText: 'Login' }).click();
await page.getByRole('link', { name: 'Salesforce', exact: true }).click();
await page.waitForTimeout(2000);
await page.getByLabel('Username').click();
await page.getByLabel('Username').fill('poornima.angiya-xwdm@force.com');
await page.getByLabel('Password').click();
await page.getByLabel('Password').fill('Poornima@1234');
await page.getByRole('button', { name: 'Log In' }).click();
await page.waitForTimeout(2000);
await page.getByRole('link', { name: 'Accounts' }).click();
await page.getByRole('button', { name: 'Accounts List' }).click();
await page.getByRole('button', { name: 'Accounts List' }).press('ArrowDown');
await page.getByRole('menuitem', { name: 'New Account' }).press('Enter');
await page.getByLabel('*Account Name').dblclick();
await page.getByLabel('*Account Name').fill('Test');
await page.getByLabel('*Account Name').fill('Test');
await page.getByRole('combobox', { name: 'Industry' }).click();
await page.getByText('Apparel').click();
await page.getByRole('group', { name: 'Billing Address' }).getByPlaceholder('Search Address').click();
await page.getByRole('group', { name: 'Billing Address' }).getByPlaceholder('Search Address').click();
await page.getByRole('group', { name: 'Billing Address' }).getByPlaceholder('Search Address').fill('sunway opus');
await page.getByTitle('SUNWAY OPUS GRAND NEVILLE-3A').click();
await page.getByLabel('Billing Street').click();
await page.getByLabel('Billing Street').fill('Test');
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.locator('#input-634').fill('9014538252');
await page.locator('#input-634').press('Tab');
await page.locator('.forcegenerated-flexipage-template > div > .slds-grid > .slds-col').click();
await page.getByRole('combobox', { name: 'Type' }).click();
await page.getByRole('combobox', { name: 'Type' }).click();
await page.getByRole('combobox', { name: 'Type' }).click();
await page.getByText('Competitor').click();
await page.getByRole('combobox', { name: 'Industry' }).click();
await page.getByText('Apparel').click();
await page.getByLabel('Website').click();
await page.getByLabel('Description').click();
await page.getByLabel('Description').fill('test description');
await page.getByRole('group', { name: 'Billing Address' }).getByPlaceholder('Search Address').click();
await page.getByRole('group', { name: 'Billing Address' }).locator('lightning-lookup-address').click();
await page.getByRole('group', { name: 'Billing Address' }).getByPlaceholder('Search Address').fill('Sunway opus');
await page.locator('#combobox-input-723-3-723').getByText('Ameenpur, Miyapur, Hyderabad').click();
await page.getByRole('group', { name: 'Shipping Address' }).getByPlaceholder('Search Address').click();
await page.getByRole('group', { name: 'Shipping Address' }).getByPlaceholder('Search Address').fill('Sunway opus ');
await page.getByRole('option', { name: 'Sunway Opus Grand Neville 3a Block-C6 Ameenpur, Miyapur, Hyderabad, Telangana,' }).locator('lightning-base-combobox-formatted-text').click();
await page.getByRole('group', { name: 'Shipping Address' }).getByPlaceholder('Search Address').click();
await page.getByRole('group', { name: 'Shipping Address' }).getByPlaceholder('Search Address').fill('Sunway Opus Grand Neville 3');
await page.getByRole('group', { name: 'Shipping Address' }).getByPlaceholder('Search Address').press('Enter');
await page.getByRole('group', { name: 'Shipping Address' }).getByPlaceholder('Search Address').press('Tab');
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.getByLabel('New Account').getByText('Save', { exact: true }).click();
await page.getByRole('button', { name: 'Save', exact: true }).click();
//create new opportunity
await page.getByRole('link', { name: 'Opportunities' }).click();
await page.getByRole('button', { name: 'New' }).click();
await page.locator('lightning-grouped-combobox').filter({ hasText: '*Account Name' }).locator('svg').click();
await page.getByLabel('Recent Accounts').locator('span').nth(2).click();
await page.getByLabel('*Opportunity Name').click();
await page.getByLabel('*Opportunity Name').fill('TestOpportunityPoor');
await page.getByLabel('Amount').fill('');
await page.getByLabel('*Opportunity Name').press('Tab');
await page.getByLabel('Amount').press('Tab');
await page.getByRole('button', { name: 'Select a date for Close Date' }).click();
await page.getByLabel('-10-11').getByRole('button', { name: '11' }).click();
await page.getByRole('combobox', { name: 'Stage' }).click();
await page.getByTitle('Negotiation').click();
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.locator('button').filter({ hasText: 'Mark Stage as Complete' }).click();
await page.getByLabel('Stage*').selectOption('Closed Won');
await page.getByRole('button', { name: 'Save' }).click();
await page.getByText('EditKey Fields', { exact: true }).click();
await page.getByRole('textbox', { name: 'Amount' }).click();
await page.getByRole('textbox', { name: 'Amount' }).fill('2000');
await page.getByRole('button', { name: 'Save' }).click();await page.getByRole('link', { name: 'Opportunities' }).click();
await page.getByRole('link', { name: 'TestOpportunityPoor' }).click();
await page.getByLabel('Upload FilesOr drop files').setInputFiles([]);
await page.getByText('Upload Files', { exact: true }).click();
await page.getByLabel('Upload FilesOr drop files').setInputFiles('error.txt');
await page.getByRole('button', { name: 'Done' }).click();
await page.getByLabel('New Event').click();
await page.getByRole('button', { name: 'Maximize' }).click();
await page.getByLabel('*Subject').click();
await page.getByText('Call', { exact: true }).click();
await page.getByLabel('Description').click();
await page.getByLabel('Description').fill('test');
await page.getByRole('button', { name: 'Save' }).click();
await page.getByRole('link', { name: 'Opportunities', exact: true }).click();
await page.getByRole('link', { name: 'TestOpportunityPoor' }).click();



});