import {expect, test} from '@playwright/test';
import {faker} from '@faker-js/faker';
import { KeyObject } from 'crypto';
test('login ',async ({page}) => {
await page.goto('https://login.salesforce.com//');
await page.fill('input[name="username"]',"sivarani.gurram-jb7g@force.com");
await page.fill('input[name="pw"]',"Test@1234");
await page.click('input[name="Login"]');
await page.click('text="Accounts"');
//await page.locator("(//span[text()='Accounts'])[4])").waitFor({state:'visible'});
//await page.waitForSelector('button[title="New"]')
await page.locator("//a[@title='New']").click();
const accName = faker.person.firstName();
await page.fill('input[name="Name"]',accName );
await page.fill('input[name="Website"]', "TestAccount1@Test1.com");
await page.locator("//button[@aria-label='Type']").click();
await page.locator("//lightning-base-combobox-item[@data-value='Investor']").click({delay:2000});
await page.locator("//label[text()='Description']/following-sibling::div/textarea").fill('TestAccoiunt');
//await page.locator("button[@name='Type']").selectOption({value:"Analyst"});
//await page.fill('input[name="label-end"]',"Test");
await page.fill('input[name="Phone"]',"Test");
await page.locator("//label[text()='Billing Street']/following-sibling::div/textarea").fill('TestAccoiunt');
await page.fill('input[name="city"]',"Test");
await page.fill('input[name="postalCode"]',"TestAccount");
await page.fill('input[name="province"]',"Testprovinince");
await page.fill('input[name="country"]',"Testcountry");
await page.locator("//label[text()='Shipping Street']/following-sibling::div/textarea").fill('TestAccoiunt');
await page.locator("//label[text()='Shipping City']/following-sibling::div/input").fill('ShippingCity');
await page.locator("//label[text()='Shipping City']/following-sibling::div/input").fill('ShippingCity');
await page.locator("//label[text()='Shipping Zip/Postal Code']/following-sibling::div/input").fill('600082');
await page.locator("//label[text()='Shipping State/Province']/following-sibling::div/input").fill('CA');
await page.locator("//label[text()='Shipping Country']/following-sibling::div/input").fill('ShippingCountry');
await page.pause();
await page.locator("//button[@name='SaveEdit']").scrollIntoViewIfNeeded();
await page.locator("//button[@name='SaveEdit']").waitFor({state:'visible'});
await page.locator("//button[@name='SaveEdit']").click();
//await page.pause();
await page.goto('https://innovation-data-2814.lightning.force.com/lightning/o/Opportunity/list?filterName=AllOpportunities');
//await page.click('text="Sales"');
await page.getByTitle("Opportunities").first().click({delay:2000});
await page.waitForLoadState("load");
await page.locator("//a[@title='New']").click({force:true});
await page.waitForTimeout(2000);
const oppName = faker.person.lastName()
await page.fill('input[name="Name"]',oppName,{timeout:3000});
await page.locator("//label[text()='Account Name']/following-sibling::div//input").fill(accName,{timeout:2000});
await page.locator("//label[text()='Account Name']/following-sibling::div//input").click();
//await page.locator("//div[@role='listbox']/ul/li").first().click({delay:2000});
await page.locator("//div[@role='listbox']/ul/li").first().click({delay:2000});
await page.locator("//button[@aria-label='Stage']").click();
await page.locator("//lightning-base-combobox-item[@data-value='Qualify']").click({delay:2000});
await page.fill('input[name="CloseDate"]',"10/09/2024");
await page.fill('input[name="Amount"]',"200");
await page.fill('input[name="NextStep"]',"NextStep");
await page.locator("//label[text()='Description']/following-sibling::div/textarea").fill('TestAccoiunt');
await page.locator("//button[@name='SaveEdit']").click({delay:2000});
await page.locator("//span[text()='Mark Stage as Complete']").click();
//await page.locator("//button[@value='NewEvent']").nth(2).click();
//await page.locator("//label[text()='Subject']/following-sibling::div//input").click();
await page.getByLabel('New Event').click();
await page.getByLabel('Subject').click();
await page.locator("//span[text()='Call']").click();
//await page.locator("//label[text()='Description']/following-sibling::div/textarea").fill('TestEvent');
await page.getByRole('button', { name: 'Save' }).click();
await page.locator("//span[text()='Mark Stage as Complete']").click();
await page.getByLabel('Log a Call').click();
await page.getByRole('button', { name: 'Save' }).click();
await page.getByLabel('New Task').click();
await page.getByLabel('Subject').fill('Send Letter');
//await page.locator("//span[text()='Send Letter']").click();
//await page.getByLabel('Due Date').click();
//await page.fill('input[name="DueDate"]',"18/09/2024");
await page.getByRole('button', { name: 'Save' }).click();
await page.locator("//span[text()='Mark Stage as Complete']").click();
await page.locator("//input[@name='fileInput']").last().setInputFiles('C:/Users/GurramSivarani/OneDrive - Fint solutions Pvt Ltd/Desktop/Sample/Sample.jpg');
await page.locator("//lightning-icon[@icon-name='utility:success']").first().waitFor({state:"visible"});
await page.locator("//button[@aria-live='off'] //span[text()='Done']").click();
await page.locator("//span[text()='Mark Stage as Complete']").waitFor({state:"visible"});
await page.locator("//span[text()='Mark Stage as Complete']").click();
await page.pause();
await page.locator("//input[@class='slds-combobox__input slds-input']").click();
await page.locator("//lightning-base-combobox-item[@data-value='Closed Won']").click({delay:2000});
await page.getByRole('button', { name: 'Save' }).click();
await page.pause();
//await page.locator("//span[text()='Save']//parent::button").nth(3).click();
})